### ISSUE TITLE
runtasks not found

### ISSUE THREAD

**Issue by ernop** [hzdg/django-periodically#1]
I've installed this but it doesn't seem to be copying over the management task - I get Unknown command: runtasks not found errors when following the instruction steps.  i.e.:

```
install
add to installed_apps
syncdb
python manage.py runtasks  --> error
```

**Comment by ernop** [comment]
Hmm, the management folder into my project folder works, but then there's an import error in runtasks.  That can be fixed by changing the imports to import from the globally installed periodically instead of a relative package (which is not where they will be...)

from periodically import register as task_scheduler
#from ... import register as task_scheduler

from periodically.utils import get_scheduler_backends_in_groups
#from ...utils import get_scheduler_backends_in_groups

Forgive me if I haven't understood the right way to install a package...

**Comment by matthewwithanm** [comment]
Hm. Sounds like you may not be installing the package correctly. Are you saying that you've moved the management folder from the periodically repo into your project? If so, that's not right; the entire "periodically" package needs to remain together. The recommended way to install a python package is to [use pip](https://github.com/hzdg/django-periodically#installation), but if you can't do that, you could drop the entire "periodically" folder into some place on your python path.

**Comment by ernop** [comment]
Thanks! Yeah, I ended up just copying the whole folder as an app, plus manually copying the management folder from here.

It is strange, I installed with pip as explained in the instructions (and as I usually install things), which installed the package into my site-packages directory as I expected (I could import it) - but it didn't copy it to my project folder as an app - is that something that's supported?

i.e. I thought pip installs packages for python in general, not as apps within a django install.

Anyway I ended up getting it working.

**Comment by matthewwithanm** [comment]
> Yeah, I ended up just copying the whole folder as an app, plus manually copying the management folder from here.

Just copying the whole "periodically" folder should to your python path (or pip installing) should be enough; no need to move or copy the management folder independently (in fact, it can't work outside of the "periodically" folder).

> It is strange, I installed with pip as explained in the instructions (and as I usually install things), which installed the package into my site-packages directory as I expected (I could import it) - but it didn't copy it to my project folder as an app - is that something that's supported?
> 
> i.e. I thought pip installs packages for python in general, not as apps within a django install.

You're right: pip is for Python in general, not Django specifically. But Django apps are just special Python packages (i.e. Python packages that contain a models module). So there's really no need to copy it into your project folder; it just needs to be on your Python path. Generally, what people do is create a [virtualenv](http://pypi.python.org/pypi/virtualenv/) for each project and install dependencies into that. Then, dependencies are listed in a requirements.txt file in your project so that they can be easily installed by somebody who wants to use your project. Of course, you could also bundle all of the dependencies with your project, but, given the obvious drawbacks, very few do that.
